from enum import Enum
from typing import Dict, List

class HuntState(str, Enum):
    INTAKE = "INTAKE"
    VERIFIED = "VERIFIED"
    COMPLIANCE_PENDING = "COMPLIANCE_PENDING"
    PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED"
    GOVERNANCE_REVIEW = "GOVERNANCE_REVIEW"
    EXPORT_APPROVED = "EXPORT_APPROVED"
    EXPORTED = "EXPORTED"

ALLOWED_TRANSITIONS: Dict[HuntState, List[HuntState]] = {
    HuntState.INTAKE: [HuntState.VERIFIED],
    HuntState.VERIFIED: [HuntState.COMPLIANCE_PENDING],
    HuntState.COMPLIANCE_PENDING: [HuntState.PAYMENT_CONFIRMED, HuntState.GOVERNANCE_REVIEW],
    HuntState.PAYMENT_CONFIRMED: [HuntState.GOVERNANCE_REVIEW],
    HuntState.GOVERNANCE_REVIEW: [HuntState.EXPORT_APPROVED],
    HuntState.EXPORT_APPROVED: [HuntState.EXPORTED]
}
