"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ComparisonResult } from "@/lib/comparison/comparison-runner";

export default function AuditPage() {
  const params = useParams();
  const comparisonId = params.id as string;

  const [result, setResult] = useState<ComparisonResult | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const fetchAudit = async () => {
      try {
        const res = await fetch(`/api/comparisons/${comparisonId}`);
        if (!res.ok) {
          setError("Failed to fetch audit data");
          return;
        }
        const data = await res.json();
        setResult(data);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Unknown error");
      } finally {
        setIsLoading(false);
      }
    };

    if (comparisonId) fetchAudit();
  }, [comparisonId]);

  const handleCopyHash = () => {
    if (result?.evidenceHash) {
      navigator.clipboard.writeText(result.evidenceHash);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 px-4 py-8">
        <div className="max-w-6xl mx-auto">
          <p className="text-center text-gray-600">Loading audit data...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 px-4 py-8">
        <div className="max-w-6xl mx-auto">
          <div className="bg-red-50 dark:bg-red-900 p-4 rounded text-red-800 dark:text-red-200">
            {error}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 px-4 py-8">
      <div className="max-w-6xl mx-auto">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-8">Audit Trail</h1>

        <div className="mb-6 rounded border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-700 dark:bg-amber-950 dark:text-amber-100">
          SIMULATED DATA — NOT LIVE FARES. Audit entries are generated by mock provider and mock network verification unless live mode is configured.
        </div>

        {/* Evidence Hash */}
        <div className="bg-white dark:bg-gray-800 rounded-lg p-6 mb-6">
          <h2 className="text-lg font-semibold mb-4">Evidence Hash</h2>
          <div className="flex items-center gap-2">
            <code className="flex-1 bg-gray-100 dark:bg-gray-900 p-3 rounded text-xs font-mono break-all">
              {result?.evidenceHash}
            </code>
            <button
              onClick={handleCopyHash}
              className="px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white rounded transition"
            >
              {copied ? "✓ Copied" : "Copy"}
            </button>
          </div>
          <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">
            SHA256 hash of the complete comparison data. Use this to verify data integrity.
          </p>
        </div>

        {/* Comparison Status */}
        <div className="bg-white dark:bg-gray-800 rounded-lg p-6 mb-6">
          <h2 className="text-lg font-semibold mb-4">Status</h2>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-sm text-gray-600 dark:text-gray-400">Status</p>
              <p className="text-lg font-bold text-gray-900 dark:text-white">{result?.status}</p>
            </div>
            <div>
              <p className="text-sm text-gray-600 dark:text-gray-400">Completed At</p>
              <p className="text-lg font-bold text-gray-900 dark:text-white">
                {result?.completedAt ? new Date(result.completedAt).toLocaleString() : "N/A"}
              </p>
            </div>
          </div>
        </div>

        {/* Errors */}
        {result?.errors && Object.keys(result.errors).length > 0 && (
          <div className="bg-red-50 dark:bg-red-900 rounded-lg p-6 mb-6">
            <h2 className="text-lg font-semibold text-red-900 dark:text-red-100 mb-4">Errors</h2>
            <div className="space-y-2">
              {Object.entries(result.errors).map(([key, message]) => (
                <div key={key} className="text-sm text-red-800 dark:text-red-200">
                  <strong>{key}:</strong> {message}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Matched Results */}
        {result?.matchedResults && result.matchedResults.length > 0 && (
          <div className="bg-white dark:bg-gray-800 rounded-lg p-6 mb-6">
            <h2 className="text-lg font-semibold mb-4">Matched Results</h2>
            <div className="space-y-4">
              {result.matchedResults.map((r, idx) => (
                <div key={idx} className="border border-gray-200 dark:border-gray-700 p-4 rounded">
                  <div className="flex justify-between items-start mb-2">
                    <div>
                      <p className="font-semibold">{r.locationLabel}</p>
                      <p className="text-xs text-gray-500 dark:text-gray-400">{r.locationKey}</p>
                    </div>
                    <span
                      className={`px-2 py-1 rounded text-xs font-medium ${
                        r.status === "MATCHED"
                          ? "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200"
                          : "bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200"
                      }`}
                    >
                      {r.status}
                    </span>
                  </div>
                  {r.normalizedPrice && (
                    <div className="text-sm text-gray-600 dark:text-gray-400">
                      <p>
                        Normalized Price: <strong>{r.normalizedPrice.toFixed(2)} {r.normalizedCurrency}</strong>
                      </p>
                      {r.matchConfidence && <p>Match Confidence: {r.matchConfidence}</p>}
                      {r.error && <p className="text-red-600 dark:text-red-400">Error: {r.error}</p>}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Raw Data */}
        <div className="bg-white dark:bg-gray-800 rounded-lg p-6">
          <h2 className="text-lg font-semibold mb-4">Raw Data</h2>
          <pre className="bg-gray-100 dark:bg-gray-900 p-4 rounded text-xs font-mono overflow-auto max-h-96">
            {JSON.stringify(result, null, 2)}
          </pre>
        </div>
      </div>
    </div>
  );
}
